services:
  pg:
    image: postgres:16.2-alpine3.19
    container_name: pg
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - pg_network
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_PASSWORD=devsecret
    ports:
      - "5432:5432"


volumes:
  pg_volume:
    name: pg_volume


networks:
  pg_network:
    name: pg_network
    driver: bridge
